### ISSUE TITLE
SyntaxError Unexpected token, expected "}" (22:4)

### ISSUE THREAD

**Issue by freakkiller** [robinscholz/svelte-inline-svg#9] opened 2021-04-13 11:33 UTC
The build process using 'rush build' keeps aborting because line 22 of the inline-svg.svelte file expects a "}" instead of the "return obj". This error occurs in both version 1.0.8 and 1.0.7.

**Comment by robinscholz** [comment] 2021-04-13 11:37
@freakkiller 

Could you provide more info about what you are trying to do with `rush build`? I'm not familiar with this command.

**Comment by freakkiller** [comment] 2021-04-13 11:52
Oh, we use rush from microsoft to build our monorepos. With rush build there will be executed 'pnpm run build-prod' witch loads 'rollup -c --silent"

**Comment by robinscholz** [comment] 2021-04-13 13:41
@freakkiller could you setup a repository with a reproduction of the issue? I cannot reproduce the issue locally here.

**Comment by freakkiller** [comment] 2021-04-14 10:49
Creating your own repository will not be possible. I think that the problem may be caused by Babel. We don't support the JSX format, so I have to translate your package using Babel plugins. Possibly this is where the error occurs.

**Comment by robinscholz** [comment] 2021-04-14 11:43
I'm afraid this is out of the scope of this repository then. For what its worth, I tried running the `build` command with pnpm locally and that works just like with npm, npx and yarn.

I'll close this issue for now.

**Closed by robinscholz** 2021-04-14 11:43 UTC
